version: "3"

services:
  test-debian:
    command: apache2ctl -D FOREGROUND
    build: .
    ports:
      - "8080:80"
      - "8082:82"
      - "8088:88"
      - "8089:89"
      - "8443:443"
      - "8444:444"
    volumes:
      - ./config/apache/var/www:/var/www
      - ./config/apache/etc/apache2/sites-available:/etc/apache2/sites-enabled
      - ./config/apache/etc/apache2/ports.conf:/etc/apache2/ports.conf
      - ./config/nginx/etc/nginx/sites-enabled/default:/etc/nginx/sites-enabled/default
      - ./config/nginx/etc/nginx/sites-enabled/proxy:/etc/nginx/sites-enabled/proxy

    stdin_open: true
    tty: true
